codecov:
  require_ci_to_pass: true

coverage:
  precision: 2
  round: down
  range: "70...100"

  status:
    project:
      default:
        target: 85%
        threshold: 5%
        informational: false
    patch:
      default:
        target: 75%
        threshold: 10%
        informational: false

comment:
  layout: "reach, diff, flags, files"
  behavior: default
  require_changes: true

